AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para crear instancias EC2 con grupos de seguridad, usando un VPC existente  y asignando IP privadas concretas."

Resources:
  EC2SecurityGroupHAProxy:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: "HAProxy"
      GroupDescription: "Grupo de seguridad para HAProxy"
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"

  EC2SecurityGroupMatrix:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: "HAProxy-Matrix"
      GroupDescription: "Grupo de seguridad para Matrix Synapse"
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 8008
          ToPort: 8008
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 8448
          ToPort: 8448
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"

  EC2SecurityGroupWordpress:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: "Wordpress-Tickets"
      GroupDescription: "Grupo de seguridad para Tickets Wordpress"
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"

  EC2SecurityGroupPostgres:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: "Postgres-Matrix"
      GroupDescription: "Grupo de seguridad para Postgres"
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: "0.0.0.0/0"

  NetworkInterfaceHAProxyMatrix:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue PublicSubnet1Id
      PrivateIpAddress: "10.215.1.10"
      Description: "Network Interface for HAProxy-Matrix"
      GroupSet:
        - !Ref EC2SecurityGroupHAProxy
      Tags:
        - Key: Name
          Value: "HAProxy-Matrix-Interface"
      
  NetworkInterfaceHAProxyWordpress:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue PublicSubnet2Id
      PrivateIpAddress: "10.215.2.10"
      Description: "Network Interface for Wordpress"
      GroupSet:
        - !Ref EC2SecurityGroupHAProxy
      Tags:
        - Key: Name
          Value: "HAProxy-Wordpress-Interface"

  NetworkInterfaceMatrix1:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue PrivateSubnet1Id
      PrivateIpAddress: "10.215.3.20"
      Description: "Network Interface for Matrix"
      GroupSet:
        - !Ref EC2SecurityGroupMatrix
      Tags:
        - Key: Name
          Value: "Matrix-Interface1"

  NetworkInterfaceMatrix2:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue PrivateSubnet1Id
      PrivateIpAddress: "10.215.3.21"
      Description: "Network Interface for Matrix"
      GroupSet:
        - !Ref EC2SecurityGroupMatrix
      Tags:
        - Key: Name
          Value: "Matrix-Interface2"

  NetworkInterfacePostgres1:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue PrivateSubnet1Id
      PrivateIpAddress: "10.215.3.100"
      Description: "Network Interface for Postgres"
      GroupSet:
        - !Ref EC2SecurityGroupPostgres
      Tags:
        - Key: Name
          Value: "Postgres-Interface1"
  
  NetworkInterfacePostgres2:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue PrivateSubnet1Id
      PrivateIpAddress: "10.215.3.101"
      Description: "Network Interface for Postgres"
      GroupSet:
        - !Ref EC2SecurityGroupPostgres
      Tags:
        - Key: Name
          Value: "Postgres-Interface2"

  NetworkInterfaceWordpress1:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue PrivateSubnet2Id
      PrivateIpAddress: "10.215.4.20"
      Description: "Network Interface for Wordpress"
      GroupSet:
        - !Ref EC2SecurityGroupWordpress
      Tags:
        - Key: Name
          Value: "Wordpress-Interface1"

  NetworkInterfaceWordpress2:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue PrivateSubnet2Id
      PrivateIpAddress: "10.215.4.21"
      Description: "Network Interface for Wordpress"
      GroupSet:
        - !Ref EC2SecurityGroupWordpress
      Tags:
        - Key: Name
          Value: "Matrix-Interface2"

  EC2InstanceHAProxyMatrix:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-04b4f1a9cf54c11d0"
      KeyName: "ssh-mensagl-2025-rufino"
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfaceHAProxyMatrix
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            VolumeSize: 16
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: "HAProxy-Matrix"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          mkdir /home/ubuntu/duckdns
          cd /home/ubuntu/duckdns
          # Poner entre las comillas el echo url=...
          echo 'echo url=" | curl -k -o ~/duckdns/duck.log -K -' > duck.sh
          chmod 700 duck.sh
          tarea="*/5 * * * * /home/ubuntu/duckdns/duck.sh >/dev/null 2>&1"
          # Añade la tarea cron al crontab actual
          (crontab -l 2>/dev/null; echo "$tarea") | crontab -
          ./duck.sh

  EC2InstanceHAProxyWordpress:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-04b4f1a9cf54c11d0"
      KeyName: "ssh-mensagl-2025-rufino"
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfaceHAProxyWordpress
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            VolumeSize: 16
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: "HAProxy-Wordpress"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          mkdir /home/ubuntu/duckdns
          cd /home/ubuntu/duckdns
          # Poner entre las comillas el echo url=...
          echo 'echo url="" | curl -k -o ~/duckdns/duck.log -K -' > duck.sh
          chmod 700 duck.sh
          tarea="*/5 * * * * /home/ubuntu/duckdns/duck.sh >/dev/null 2>&1"
          # Añade la tarea cron al crontab actual
          (crontab -l 2>/dev/null; echo "$tarea") | crontab -
          ./duck.sh
  EC2InstanceMatrix1:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-04b4f1a9cf54c11d0"
      KeyName: "ssh-mensagl-2025-rufino"
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfaceMatrix1
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            VolumeSize: 16
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: "Matrix1"

  EC2InstanceMatrix2:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-04b4f1a9cf54c11d0"
      KeyName: "ssh-mensagl-2025-rufino"
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfaceMatrix2
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            VolumeSize: 16
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: "Matrix2"
  
  EC2InstancePostgres1:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-0e1bed4f06a3b463d"
      KeyName: "ssh-mensagl-2025-rufino"
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfacePostgres1
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            VolumeSize: 16
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: "Postgres-Matrix1"

  EC2InstancePostgres2:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-0e1bed4f06a3b463d"
      KeyName: "ssh-mensagl-2025-rufino"
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfacePostgres2
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            VolumeSize: 16
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: "Postgres-Matrix2"
  
  EC2InstanceWordpress1:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-04b4f1a9cf54c11d0"
      KeyName: "ssh-mensagl-2025-rufino"
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfaceWordpress1
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            VolumeSize: 16
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: "Wordpress1"

  EC2InstanceWordpress2:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-04b4f1a9cf54c11d0"
      KeyName: "ssh-mensagl-2025-rufino"
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfaceWordpress2
          DeviceIndex: "0"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            VolumeSize: 16
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: "Wordpress2"

  # New Grupo de seguridad para RDS
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: "MySQL-RDS"
      GroupDescription: "Grupo de seguridad para RDS MySQL allowing EC2 access"
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SecurityGroupWordpress  # Allowing Wordpress EC2 to access the RDS MySQL DB

  # MySQL RDS Instance
  MySQLRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: wordpress      # Nombre de usuario en texto plano
      MasterUserPassword: Admin123   # Contraseña en texto plano
      DBName: wordpress
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup      # Assigning the RDS Security Group
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      BackupRetentionPeriod: 7
      Tags:
        - Key: Name
          Value: "MySQL-Wordpress-RDS"
      DBSubnetGroupName: !Ref DBSubnetGroup

  # DB Subnet Group for RDS
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS instances"
      SubnetIds: 
        - !ImportValue PrivateSubnet1Id
        - !ImportValue PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: "RDS-SubnetGroup"

Outputs:
  InstanceHAProxyMatrix1Id:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref EC2InstanceHAProxyMatrix

  InstanceHAProxyWordpress1Id:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref EC2InstanceHAProxyWordpress

  InstanceMatrix1Id:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref EC2InstanceMatrix1

  InstanceMatrix2Id:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref EC2InstanceMatrix2

  InstancePostgres1Id:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref EC2InstancePostgres1

  InstancePostgres2Id:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref EC2InstancePostgres2

  InstanceWordpress1Id:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref EC2InstanceWordpress1

  InstanceWordpress2Id:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref EC2InstanceWordpress2

  RDSInstanceEndpoint:
    Description: "RDS MySQL Endpoint"
    Value: !GetAtt MySQLRDS.Endpoint.Address

  EC2SecurityGroupHAProxyId:
    Description: "Security Group ID"
    Value: !Ref EC2SecurityGroupHAProxy

  EC2SecurityGroupMatrixId:
    Description: "Security Group ID"
    Value: !Ref EC2SecurityGroupMatrix
  
  EC2SecurityGroupWordpressId:
    Description: "Security Group ID"
    Value: !Ref EC2SecurityGroupWordpress
  
  EC2SecurityGroupPostgresId:
    Description: "Security Group ID"
    Value: !Ref EC2SecurityGroupPostgres
  
  RDSSecurityGroupId:
    Description: "Security Group ID for RDS"
    Value: !Ref RDSSecurityGroup
